export { getFeaturedProducts } from './application/get-featured-products'
export { isHighDemandProduct, isProductAvailable, type Product } from './domain/product'
export type { ProductRepository } from './domain/product-repository'
export { backendAProductRepository } from './infrastructure/adapters/backend-a/backend-a-product-repository'
export { mockProductRepository } from './infrastructure/adapters/mock/mock-product-repository'
export { provideProductRepository, useProductRepository } from './infrastructure/product-repository-provider'
export { default as ProductCard } from './ui/ProductCard.vue'
